apiVersion: v1
kind: Service
metadata:
  name: fancollector-react
spec:
  type: LoadBalancer
  selector:
    app: fancollector
    tier: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 