apiVersion: apps/v1
kind: Deployment
metadata:
  name: fancollector-react
  labels:
    app: fancollector
    tier: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fancollector
      tier: react
  template:
    metadata:
      labels:
        app: fancollector
        tier: react
    spec:
      containers:
        - name: fancollector-react
          # CAMBIAR LA VERSIÓN EN FUNCION DE LA NECESIDAD!
          image: a28731nerea/fancollector-react:v3
          ports:
            - containerPort: 80
 